name: Code Quality

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v3
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          list-files: shell
          filters: |
            python:
              - added|modified: '*.py'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/requirements.txt
      - name: Analysing the code with flake8
        if: steps.changes.outputs.python == 'true'
        run: |
          flake8 ${{ steps.changes.outputs.python_files }} --config ${{ github.workspace }}/.flake8
      - name: Analysing the code with black
        if: steps.changes.outputs.python == 'true'
        run: |
          black ${{ steps.changes.outputs.python_files }}
      - name: Analysing imports with isort and black
        if: steps.changes.outputs.python == 'true'
        run: |
          isort ${{ steps.changes.outputs.python_files }} --profile black
      - name: Analysing the code with mypy
        if: steps.changes.outputs.python == 'true'
        run: |
          mypy ${{ steps.changes.outputs.python_files }} --pretty
      - name: Analysing the code with bandit
        if: steps.changes.outputs.python == 'true'
        run: |
          bandit ${{ steps.changes.outputs.python_files }}
