name: Pylint

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v3
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          list-files: shell
          filters: |
            python:
              - added|modified: '*.py'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/requirements.txt
      - name: Analysing the code with pylint
        if: steps.changes.outputs.python == 'true'
        run: |
          pylint ${{ steps.changes.outputs.python_files }} --rcfile ${{ github.workspace }}/.pylintrc
      - name: Analysing the code with black
        if: steps.changes.outputs.python == 'true'
        run: |
          black ${{ steps.changes.outputs.python_files }} --diff --color
