name: Pylint

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11.1
        uses: actions/setup-python@v3
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            py:
              - '**/*.py'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/requirements.txt
      - name: Analysing the code with pylint
        if: steps.changes.outputs.py == 'true'
        run: |
          pylint --reports=n --output-format=json --rcfile .pylintrc $(git ls-files '*.py') --files ${{ steps.changes.outputs.py_files }}
      - name: Analysing the code with black
        if: steps.changes.outputs.py == 'true'
        run: |
          black --files ${{ steps.changes.outputs.py_files }}
